title: "Slack でアプリ開発を始めよう"
summary: "Slack を使ってアプリ開発を始める方法"
topics: ["slack", "slackbot", "expo", "expogo", "typescript", "reactnative"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
